name: 'get credit everyday'

on:
  push:
  schedule:
    - cron: '9 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          pwd
          ls
          sudo apt-get update
          sudo apt-get -y install tesseract-ocr
          pip3 install -r requirements.txt

      - name: run the script
        run: |
          cd src && python3 service.py ${{ secrets.USERS }}
