name: 'get credit everyday'

on:
  push:
  schedule:
    - cron: '9 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo /bin/bash prepare.sh

      - name: run the script
        run: |
          cd src && python3 service.py "${{ secrets.USERS }}"
